name: "Maitri's Art Gallery"
author: "Maitri Patel"
heading: "This is my Art Gallery"
favicon: "assets/img/favicon.ico"
logo: "assets/img/logo.png"
email: "maitri@email.com"
description: "the digital collection of my arts"
defaults:
  - scope:
      path: "arts/"
    values:
      image: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-books
