name: Maitri Patel
title: Maitri's Art Gallery
heading: This is my Art Gallery
favicon: assets/img/favicon.ico
logo: assets/img/logo.png
email: maitri@email.com
description: i'm ma
url: 
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-books
