name: entrier

on: 
  push:
    paths: 
      - 'arts/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lots0logs/gh-action-get-changed-files@2.0.6
        with:
          token: ${{secrets.GH_PAT}}
